### ISSUE TITLE
In teaser image, hovering over spatial locations doesn't change the feature visualization

### ISSUE THREAD

**Issue by hypotext** [distillpub/post--building-blocks#17]
The interface design figure says: "For instance, let us consider our teaser ﬁgure again. (...) hovering over spatial locations gives us neuron-speciﬁc attribution." Perhaps I misunderstood the caption, but the figure shows a bidirectional arrow between image and feature visualization, so I thought hovering over the image would change the feature visualization, but it doesn't seem to change anything. Here's what I see:

![distill](https://user-images.githubusercontent.com/2762356/37130151-39ccfb06-2250-11e8-9b4d-edde002605cb.gif)

Using Chrome on macOS. No obvious console errors.

**Comment by ludwigschubert** [comment]
@hypotext you're right—we removed this feature pretty much last minute as the attribution wasn't normalized and so all the values where too small to really see. @arvind is probably best suited to decide what we should do here—either remove the text mentioning it, or add back the feature (it's just disabled through CSS) and rethink how we display the magnitudes in a humanely meaningful way.

**Comment by arvind** [comment]
Thanks @hypotext. Fixed with 46dbec6 to make the teaser design space diagrams to reflect the final behavior of the teaser figure. As @ludwigschubert mentioned, we got rid of the neuron attribution because they were incorrect (and tedious to recompute).
