### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by lemairecarl** [distillpub/post--building-blocks#18]
In the last paragraph of the section "How Trustworthy Are These Interfaces?":

https://github.com/distillpub/post--building-blocks/blob/778a8deab1d0d1769745e1ae5a2ad8959d0d2872/public/index.html#L877

Trusting our interfaces is **essentially** for many of the ways we want to use interpretability.

Should it be "essential"?

**Comment by ludwigschubert** [comment]
Thanks for catching this, @lemairecarl !
