### ISSUE TITLE
Some errors in "Spatial Attribution with Saliency Maps" visualization

### ISSUE THREAD

**Issue by DeepVoltaire** [distillpub/post--building-blocks#19]
Hi, great article! I found some small errors that some people maybe stumple upon when going in detail through the "Spatial Attribution with Saliency Maps" visualization:

1. When seleting the image of the hog and clicking on "center of the snout" in the description a piece in the center of the hog is selected and not the center of the snout.
![screenshot from 2018-03-11 17-42-32](https://user-images.githubusercontent.com/15069697/37256074-295ee7da-2556-11e8-9d1d-317e4a9e96ec.png)

You probably mean this center of the snout location
![screenshot from 2018-03-11 17-43-01](https://user-images.githubusercontent.com/15069697/37256099-6cf363e0-2556-11e8-9d0c-a29f9e325f9f.png)

2. Same thing when clicking on "right ear" in the description: It shows a location which is centered on the right eye and not the ear.

![screenshot from 2018-03-11 17-53-33](https://user-images.githubusercontent.com/15069697/37256113-af450802-2556-11e8-8874-4034db3019e2.png)

You probably mean a position focused on the right ear like this
![screenshot from 2018-03-11 17-54-52](https://user-images.githubusercontent.com/15069697/37256122-ba445172-2556-11e8-9e83-1a3c29669653.png)

3. When selecting the image of the Brambling and clicking on "chain" in the description something weird happens. The position in the picture stays the same as the previously selected position (here on the bird head), the output attribution is a mixture of chain and brambling (which doesnt exist in the image) and the shown piece in "mixed4d" is the patch in the top left corner of the picture.

![screenshot from 2018-03-11 17-58-36](https://user-images.githubusercontent.com/15069697/37256182-846db254-2557-11e8-9fed-1ad74d7121fd.png)

I really appreciate the article, very good work. :)

**Comment by ludwigschubert** [comment]
Thanks for the report @DeepVoltaire! @arvind and me will look into this!

**Comment by DeepVoltaire** [comment]
Definitely a fast connection. Tried it also multiple times before submitting it as a bug.

**Comment by arvind** [comment]
Thanks for catching these issues, @DeepVoltaire! I've fixed them in c2507d8 -- a mix of some actual bugs (e.g., with brambling) and clarifying the caption text to better reflect the positions with the pig image.
