### ISSUE TITLE
Spritemap notebooks

### ISSUE THREAD

**Issue by robbula** [distillpub/post--building-blocks#21]
In the sprite map section of the ipython [notebook](https://colab.research.google.com/github/tensorflow/lucid/blob/master/notebooks/building-blocks/AttrChannel.ipynb) linked in `Teaser.html` it is mentioned "Check out other notebooks on how to make your own neuron visualizations." do you have any specific recommendations other than say the tensorflow deepdream [notebook](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/deepdream/deepdream.ipynb)?

**Comment by colah** [comment]
Check out the [lucid notebooks](https://github.com/tensorflow/lucid#notebooks), especially the [general tutorial on visualizing neurons](https://colab.research.google.com/github/tensorflow/lucid/blob/master/notebooks/tutorial.ipynb).

The techniques in that notebook work well enough for everything in the article, and are more or less what we originally used. However, the final spritemaps in the article use a few additional tricks and we should still write a tutorial on reproducing them exactly.

**Comment by colah** [comment]
More Lucid notebooks will be coming in the future!

**Comment by colah** [comment]
Just wanted to note that our new [differentiable parameterization](https://distill.pub/2018/differentiable-parameterizations/) article explains the [transparency trick](https://distill.pub/2018/differentiable-parameterizations/#section-rgba) we use for more focused feature visualization. Check out [the notebook](https://colab.research.google.com/github/tensorflow/lucid/blob/master/notebooks/differentiable-parameterizations/transparency.ipynb)!
