### ISSUE TITLE
MobileNet Visualization

### ISSUE THREAD

**Issue by robbula** [distillpub/post--building-blocks#22]
I have been playing around trying to visualize MobileNets using [lucid](https://github.com/tensorflow/lucid) and a couple of other tools as well. No matter the tools I'm using I am having difficulty getting meaningful results, thus I must be missing something or doing something wrong. Most of the images that come out of these techniques have results that are either vanishingly small values that go to zero when converting to an integer for visualization or are seemingly random (i.e. no discernible structure). However when I use the same tools with other networks the results are what one would expect. This is with the image value range adjusted to something appropriate for each model.

Is there something about the MobileNet architecture that causes this to be the case? Is the image value range the only values I should have to tune here or are there others as well? Have you had any success visualizing hidden layers in MobileNet? I spent sometime looking into this with some rudimentary searches and can't seem to find any posts about the issue I am seeing. The models that I have been using are VGG16, InceptionV2, and  MobileNetV1 all trained on ImageNet.

**Comment by ludwigschubert** [comment]
Hm. Here's my proposal how we may best be able to help: 
Move this issue to the [lucid repository](https://github.com/tensorflow/lucid/issues) and link to a colab notebook so we can easily reproduce. No guarantees,  but maybe it's something simple we can spot!

(Feel free to reopen if that doesn't work for any reason! :-) )
