### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by geoffwoollard** [distillpub/post--building-blocks#29]
For example, should the interface emphasize what the network recognizes, prioritize how its understanding develops, or focus on making **thing** human-scale.  --> For example, should the interface emphasize what the network recognizes, prioritize how its understanding develops, or focus on making **things** human-scale.

**Comment by ludwigschubert** [comment]
Thanks for catching that, @geoffwoollard ! :-) (Note that this fix may not yet be deployed—it will be within the next week or so.)
