### ISSUE TITLE
Small rendering issue on certain screen width

### ISSUE THREAD

**Issue by nottombrown** [distillpub/post--building-blocks#4]
![image](https://user-images.githubusercontent.com/306655/35164621-f0883f84-fcff-11e7-8e04-d0cbf0c75550.png)

**Comment by ludwigschubert** [comment]
Solved by reflowing grid at smaller screen sizes:
<img width="547" alt="screen shot 2018-03-17 at 19 54 42" src="https://user-images.githubusercontent.com/1167977/37574521-b68f14d0-2ade-11e8-8b48-06b0a72f4856.png">
